apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: rh-push-to-registry-redhat-iotest-component
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads-stage/dev-release-team-tenant/rh-push-to-registry-redhat-iotest/rh-push-to-registry-redhat-iotest-component@sha256:f6e1758ab3ea9d90b128d977e8188eefdb9380619704c01cd402f4e5932eaaf6
        name: my-python
        resources: {}
status: {}
